### ISSUE TITLE
bug: enabling cors setting leads to unwanted request filtering

### ISSUE THREAD

**Issue by pk910** [erpc/erpc#148]
**Describe the bug**
When enabling cors settings, erpc also starts filtering requests based on the whitelisted origins and returns a 403 error for non whitelisted origins.
This is not how cors is intended to work and leads to unwanted side effects with tools that use a Origin header, but do not enforce cors.

eg. Chrome extensions, which are not bound to cors, but send requests with `chrome-extension://<extension-id>` as origin.

Ideally you should not filter requests based on cors headers, just not reply any cors headers if the origin doesn't match, so the client can decide itself if its in a situation where cors is necessary.
If you rely on that filtering for some reason, you should at least make it an optional feature, which can be disabled while keeping cors headers active.

At the end, we'd like to prevent arbitrary websites from using our rpc,  but we don't want to over-block all kind of external applications.

**To Reproduce**
1. Use this erpc.yaml config:
```yaml
logLevel: debug

server:
  httpHostV4: "0.0.0.0"
  listenV6: true
  httpHostV6: "[::]"
  httpPort: 4000
  aliasing:
    rules:
      - matchDomain: "*"
        serveProject: "main"
        serveArchitecture: "evm"
        serveChain: "7078815900"

projects:
  - id: main
    cors:
      allowedOrigins:
        - "https://*.ethpandaops.io"
      allowedMethods: 
        - "GET"
        - "POST"
        - "OPTIONS"
      allowedHeaders:
        - "Content-Type"
    upstreamDefaults:
      ...
```

2. Make this request:
```bash
curl --location 'http://localhost:4000/' \
--header 'Content-Type: application/json' \
--header 'Origin: https://non-whitelisted-site.com' \
--data '{
    "method": "eth_getBlockByNumber",
    "params": [
        "0x1203319",
        false
    ],
    "id": 9199,
    "jsonrpc": "2.0"
}'
```

**Expected behavior**
The request should still be processed. The response should not contain cors headers as the origin isn't whitelisted.
