### ISSUE TITLE
"All upstream attempts failed" When upstreams return "result":[]

### ISSUE THREAD

**Issue by andreclaro** [erpc/erpc#214]
eRPC is returning `All upstream attempts failed` when all the upstreams return `{"jsonrpc":"2.0","id":1,"result":[]}`

Network: Berachain Bepolia
Chain Id: 80069

Query to one of the upstream:
```
curl -X POST https://bepolia.rpc.berachain.com \
  -H "Content-Type: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [{
      "fromBlock": "0x1ab771",
      "toBlock": "0x1ab7d5",
      "topics": ["0xbccc00b713f54173962e7de6098f643d8ebf53d488d71f4b2a5171496d038f9e"]
    }],
    "id": 1
  }'

{"jsonrpc":"2.0","id":1,"result":[]}
```

query to eRPC:
```
curl -X POST http://localhost:8080/main/evm/80069   -H "Content-Type: application/json"   -d '{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [{
      "fromBlock": "0x1ab771",
      "toBlock": "0x1ab7d5",
      "topics": ["0xcaf280c8cfeba144da67230d9b009c8f868a75bac9a528fa0474be1ba317c169"]
    }],
    "id": 1
  }'

{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"all upstream attempts failed"}}
```

eRPC Config:
```
logLevel: info

server:
  listenV4: true
  httpHostV4: "0.0.0.0"
  httpPort: 8080

database:
  evmJsonRpcCache:
    connectors:
      - id: memory-cache
        driver: memory
        memory:
          maxItems: 10000
    policies:
      - network: "*"
        method: "*"
        finality: finalized
        connector: memory-cache

metrics:
  enabled: true
  listenV4: true
  hostV4: "0.0.0.0"
  listenV6: false
  hostV6: "[::]"
  port: 8081

projects:
  - id: main
    networkDefaults:
      failsafe:
        timeout:
          duration: "30s"
        hedge:
          quantile: 0.99
          maxCount: 2
        retry:
          maxAttempts: 3
          delay: "100ms"
          jitter: "0ms"
          backoffMaxDelay: "1s"
          backoffFactor: 1.5
    upstreamDefaults:
      failsafe:
        timeout:
          duration: "15s"
        retry:
          maxAttempts: 3
          delay: "300ms"
          jitter: "100ms"
          backoffMaxDelay: "5s"
          backoffFactor: 1.5
        circuitBreaker:
          failureThresholdCount: 160
          failureThresholdCapacity: 200
          halfOpenAfter: "5m"
          successThresholdCount: 3
          successThresholdCapacity: 3
    upstreams:
      - ...
      - {'endpoint': 'https://bepolia.rpc.berachain.com'}
      - ....
```
