### ISSUE TITLE
bug: Method Ignore by Upstream configuration

### ISSUE THREAD

**Issue by aditya520** [erpc/erpc#217]
**Describe the bug**
Method Ignore by Upstream configuration

**To Reproduce**
I am trying to a simple `eth_call` on a chain. 
Hardly changed any config. Added berachain EVM

```
 - id: berachain-multi-chain-1
        endpoint: http://0.0.0.0:63874/https://rpc.berachain.com/
        evm:
          chainId: 80094
        rateLimitBudget: global
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      - id: berachain-multi-chain-2
        endpoint: http://0.0.0.0:49671/https://{$BERACHAIN-PRIVATE-RPC}/
        evm:
          chainId: 80094
        rateLimitBudget: global
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
          allowMethods:
          - "eth_call"
        autoIgnoreUnsupportedMethods: false
```

**Relevant Logs:**
```jsonl
{"level":"warn","component":"proxy","projectId":"main","networkId":"evm:80094","method":"eth_call","error":{"code":"ErrUpstreamsExhausted","message":"all upstream attempts failed (1 upstream skipped)","cause":[{"code":"ErrUpstreamRequestSkipped","message":"skipped forwarding request to upstream","details":{"upstreamId":"envio-evm:80094"},"cause":{"code":"ErrUpstreamMethodIgnored","message":"method ignored by upstream configuration","details":{"method":"eth_call","upstreamId":"envio-evm:80094"},"cause":null}}],"details":{"method":"eth_call"}},"request":{"jsonRpc":{"method":"eth_call","params":[{"data":"0x82ee990c","to":"0x36825bf3fbdf5a29e2d5148bfe7dcf7b5639e320"},"latest"],"id":8604001190165082}},"durationMs":425.910625,"time":1743709821414,"message":"failed to forward request: 1 upstream skipped"}
```

**Additional context**
Ignore the leading `0.0.0.0` as they are proxies I am running to check the request.
