### ISSUE TITLE
bug: panic on request

### ISSUE THREAD

**Issue by Zygimantass** [erpc/erpc#219]
**Describe the bug**
Panic on heavier load to the eRPC instances. Will try to get the request details shortly after submitting the issue.

**To Reproduce**
1. Use erpc version `0.0.41`
2. Use this erpc.yaml config:
```yaml
    logLevel: debug
    metrics:
      enabled: true
      listenV4: true
      listenV6: false
      hostV4: "0.0.0.0"
      port: 4001
    projects:
      - id: main
        upstreams:
        - endpoint: alchemy://${ALCHEMY_API_KEY}
        - endpoint: infura://${INFURA_API_KEY}
    database:
      evmJsonRpcCache:
        connectors:
          - id: redis
            driver: redis
            redis:
              addr: "{{ .Values.redis.address }}"
        policies:
          - network: "*"
            method: "*"
            finality: finalized
            connector: redis
      sharedState:
        connector:
          driver: redis
          redis:
            addr: "{{ .Values.redis.address }}
```
3. Push a lot of load at the eRPC instances

**Expected behavior**
No panic

**Screenshots**

**Relevant Logs:**
```jsonl
getting finalized block height: 400 Bad Request:
{
  "jsonrpc": "2.0",
  "id": null,
  "error": {
    "code": -32603,
    "message": "internal server error: unexpected server panic on per-request handler: runtime error: slice bounds out of range [900:822] stack: goroutine 4472459 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/erpc/erpc/erpc.NewHttpServer.(*HttpServer).createRequestHandler.func2.1.1()\n\t/root/erpc/http_server.go:228 +0x78\npanic({0x20f55e0?, 0xc0013b8b28?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngithub.com/bytedance/sonic/ast.(*Node).skipNextPair(0xc001033260)\n\t/go/pkg/mod/github.com/bytedance/sonic@v1.12.3/ast/parser.go:594 +0x990\ngithub.com/bytedance/sonic/ast.(*Node).skipKey(0xc001033260, {0x21c8ba3, 0x6})\n\t/go/pkg/mod/github.com/bytedance/sonic@v1.12.3/ast/node.go:1385 +0xd1\ngithub.com/bytedance/sonic/ast.(*Node).Get(0xc001033260, {0x21c8ba3, 0x6})\n\t/go/pkg/mod/github.com/bytedance/sonic@v1.12.3/ast/node.go:858 +0x4b\ngithub.com/bytedance/sonic/ast.(*Node).GetByPath(0xc00190d680?, {0xc001695400?, 0x2170d80?, 0xc003f71ad0?})\n\t/go/pkg/mod/github.com/bytedance/sonic@v1.12.3/ast/node.go:842 +0x86\ngithub.com/erpc/erpc/common.(*JsonRpcResponse).PeekStringByPath(0xc00190d680, {0xc001695400, 0x1, 0x1})\n\t/root/common/json_rpc.go:285 +0xe5\ngithub.com/erpc/erpc/architecture/evm.pickHighestBlock(0xc001290510, 0xc00126def0, {0x0, 0x0})\n\t/root/architecture/evm/eth_getBlockByNumber.go:202 +0x1cf\ngithub.com/erpc/erpc/architecture/evm.enforceHighestBlock({0x2a47fc8, 0xc0049f19d0}, {0x2a50560, 0xc0002d0fd0}, 0xc003f718c0, 0xc00126def0, {0x0, 0x0})\n\t/root/architecture/evm/eth_getBlockByNumber.go:149 +0xc9b\ngithub.com/erpc/erpc/architecture/evm.networkPostForward_eth_getBlockByNumber({0x2a47fc8?, 0xc0049f19d0?}, {0x2a50560?, 0xc0002d0fd0?}, 0xc001784b88?, 0xc0049f1ce0?, {0x0?, 0x0?})\n\t/root/architecture/evm/eth_getBlockByNumber.go:41 +0x37\ngithub.com/erpc/erpc/architecture/evm.HandleNetworkPostForward({0x2a47fc8, 0xc0049f19d0}, {0x2a50560, 0xc0002d0fd0}, 0xc003f718c0, 0xc00126def0, {0x0, 0x0})\n\t/root/architecture/evm/hooks.go:39 +0xb7\ngithub.com/erpc/erpc/erpc.(*PreparedProject).doForward(0x2a40780?, {0x2a47fc8, 0xc0049f19d0}, 0xc0002d0fd0, 0xc003f718c0)\n\t/root/erpc/projects.go:178 +0xd1\ngithub.com/erpc/erpc/erpc.(*PreparedProject).Forward(0xc000092dc0, {0x2a47fc8, 0xc0049f19d0}, {0xc00137ca80?, 0x2?}, 0xc003f718c0)\n\t/root/erpc/projects.go:146 +0x7c6\ngithub.com/erpc/erpc/erpc.NewHttpServer.(*HttpServer).createRequestHandler.func2.1(0x0, {0xc000b30000, 0x59, 0x4000}, 0xc0049f54a0, 0xc0049f5860)\n\t/root/erpc/http_server.go:333 +0xb93\ncreated by github.com/erpc/erpc/erpc.NewHttpServer.(*HttpServer).createRequestHandler.func2 in goroutine 4472457\n\t/root/erpc/http_server.go:225 +0xda5\n"
  }
}
```

With request log:
```jsonl
{"level":"info","projectId":"main","component":"proxy","projectId":"main","networkId":"evm:11155111","method":"eth_getBlockByNumber","id":547993,"ptr":"0xc0008509a0","time":1743828580629,"message":"successfully forwarded request for network"}
{"level":"error","component":"proxy","projectId":"main","networkId":"evm:11155111","time":1743828580629,"message":"unexpected server panic on per-request handler: runtime error: slice bounds out of range [42:41] stack: goroutine 12288853 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/erpc/erpc/erpc.NewHttpServer.(*HttpServer).createRequestHandler.func2.1.1()\n\t/root/erpc/http_server.go:228 +0x78\npanic({0x20f55e0?, 0xc001a8c090?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngithub.com/bytedance/sonic/ast.(*Node).skipNextPair(0xc001c7f720)\n\t/go/pkg/mod/github.com/bytedance/sonic@v1.12.3/ast/parser.go:594 +0x990\ngithub.com/bytedance/sonic/ast.(*Node).skipKey(0xc001c7f720, {0x21c8ba3, 0x6})\n\t/go/pkg/mod/github.com/bytedance/sonic@v1.12.3/ast/node.go:1385 +0xd1\ngithub.com/bytedance/sonic/ast.(*Node).Get(0xc001c7f720, {0x21c8ba3, 0x6})\n\t/go/pkg/mod/github.com/bytedance/sonic@v1.12.3/ast/node.go:858 +0x4b\ngithub.com/bytedance/sonic/ast.(*Node).GetByPath(0xc003a7ab40?, {0xc00153c370?, 0x2170d80?, 0xc000850a50?})\n\t/go/pkg/mod/github.com/bytedance/sonic@v1.12.3/ast/node.go:842 +0x86\ngithub.com/erpc/erpc/common.(*JsonRpcResponse).PeekStringByPath(0xc003a7ab40, {0xc00153c370, 0x1, 0x1})\n\t/root/common/json_rpc.go:285 +0xe5\ngithub.com/erpc/erpc/architecture/evm.pickHighestBlock(0xc001a0e7e0, 0xc001a0e5a0, {0x0, 0x0})\n\t/root/architecture/evm/eth_getBlockByNumber.go:202 +0x1cf\ngithub.com/erpc/erpc/architecture/evm.enforceHighestBlock({0x2a47fc8, 0xc0016f6e00}, {0x2a50560, 0xc0008508f0}, 0xc0002fbb80, 0xc001a0e5a0, {0x0, 0x0})\n\t/root/architecture/evm/eth_getBlockByNumber.go:149 +0xc9b\ngithub.com/erpc/erpc/architecture/evm.networkPostForward_eth_getBlockByNumber({0x2a47fc8?, 0xc0016f6e00?}, {0x2a50560?, 0xc0008508f0?}, 0xc000f72f90?, 0xc0016f6fc0?, {0x0?, 0x0?})\n\t/root/architecture/evm/eth_getBlockByNumber.go:41 +0x37\ngithub.com/erpc/erpc/architecture/evm.HandleNetworkPostForward({0x2a47fc8, 0xc0016f6e00}, {0x2a50560, 0xc0008508f0}, 0xc0002fbb80, 0xc001a0e5a0, {0x0, 0x0})\n\t/root/architecture/evm/hooks.go:39 +0xb7\ngithub.com/erpc/erpc/erpc.(*PreparedProject).doForward(0x2a40780?, {0x2a47fc8, 0xc0016f6e00}, 0xc0008508f0, 0xc0002fbb80)\n\t/root/erpc/projects.go:178 +0xd1\ngithub.com/erpc/erpc/erpc.(*PreparedProject).Forward(0xc00058e1e0, {0x2a47fc8, 0xc0016f6e00}, {0xc0015d7280?, 0x2?}, 0xc0002fbb80)\n\t/root/erpc/projects.go:146 +0x7c6\ngithub.com/erpc/erpc/erpc.NewHttpServer.(*HttpServer).createRequestHandler.func2.1(0x0, {0xc000e74000, 0x5a, 0x4000}, 0xc002b18210, 0xc002b183c0)\n\t/root/erpc/http_server.go:333 +0xb93\ncreated by github.com/erpc/erpc/erpc.NewHttpServer.(*HttpServer).createRequestHandler.func2 in goroutine 12288851\n\t/root/erpc/http_server.go:225 +0xda5\n"}
```
