### ISSUE TITLE
bug: container runs as root user

### ISSUE THREAD

**Issue by wparr-circle** [erpc/erpc#238]
**Describe the bug**
Currently erpc runs as a root user by default, this causes failures when attempting to start a pod with security context specifying to run as non root.

```yaml
securityContext:
  runAsNonRoot: true
```

```yaml
    state:
      waiting:
        message: 'container has runAsNonRoot and image will run as root (pod: "<REDACTED>",
          container: erpc)'
        reason: CreateContainerConfigError
```

The same can be determined outside of Kubernetes via:
```bash
docker run --rm ghcr.io/erpc/erpc:0.0.44 sh -c 'if [ "$(id -u)" -eq 0 ]; then echo "<0001f7e5> Running as root"; else echo "<0001f7e9> Not running as root"; fi' 
🟥 Running as root
```

Simply specifying a non-root user to run as, doesn't solve the problem either in Kubernetes
```yaml
securityContext:
  runAsUser: 1000
```

```yaml
    lastState:
      terminated:
        containerID: containerd://a1e437b361a0dfcf0f50794b918999b945c8c58949a2c8d48bc2a84f655f9a93
        exitCode: 128
        finishedAt: "2025-04-24T10:09:28Z"
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          exec: "/root/erpc-server": stat /root/erpc-server: permission denied: unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z"
```

Unfortunately it doesn't seem possible to reproduce this with docker `--user` option, which appears to be more lenient with permissions here and will allow the application to start unlike containerd.
```
docker run -it --user 1000:1000 --rm  ghcr.io/erpc/erpc:0.0.44 
```

**To Reproduce**
1. Use erpc version (e.g `0.0.44`)
2. Use the following kubernetes security context:
```yaml
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
```

**Expected behavior**
Application should start

**Screenshots**

**Relevant Logs:**
N/A

**Additional context**

Stripped k8s manifest we're running with may be found below.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: erpc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: erpc
    app.kubernetes.io/version: 0.0.43
    helm.sh/chart: erpc-0.1.0
  name: erpc
  namespace: blockchain-proxy
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: erpc
      app.kubernetes.io/name: erpc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: erpc
        app.kubernetes.io/name: erpc
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: erpc-secret
        image: ghcr.io/erpc/erpc:0.0.43
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: http
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: erpc
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthcheck
            port: http
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/erpc.yaml
          name: config
          subPath: erpc.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: erpc
        name: config
```
