### ISSUE TITLE
ERROR: ind ex row requires 14768 bytes, maximum size is 8191 (SQLSTATE 54000)

### ISSUE THREAD

**Issue by lazydefi1** [erpc/erpc#241]
Hello!

I'm trying to cache requests with postgres and got a lot of errors in the log like this one:

``erpc_service  | {"level":"warn","projectId":"main","component":"proxy","networkId":"evm:1","method":"eth_getBlockByNumber","id":5520,"ptr":"0x40005c7e40","error":"ERROR: ind
ex row requires 14768 bytes, maximum size is 8191 (SQLSTATE 54000)","time":1745743284795,"message":"could not store response in cache"}``

Any idea how to fix this?

Thanks!

Here is my `docker-compose.yml` file (just in case):

```
version: '3.8'

services:
  erpc:
    image: ghcr.io/erpc/erpc:latest
    container_name: erpc_service
    restart: unless-stopped # Ensures restart on failure or host reboot
    ports:
      - "4000:4000" # RPC port
      - "4001:4001" # Metrics port
    volumes:
      - ./erpc.yaml:/root/erpc.yaml # Mount your config file
    environment:
      # Pass secrets/config from host environment to the container
      - ERPC_MAIN_SECRET=${ERPC_MAIN_SECRET}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ERPC_USER=${POSTGRES_ERPC_USER}
      - POSTGRES_ERPC_PASSWORD=${POSTGRES_ERPC_PASSWORD}
      - POSTGRES_ERPC_DB=${POSTGRES_ERPC_DB}
    depends_on:
      postgres:
        condition: service_healthy # Wait for Postgres to be ready before starting eRPC
    networks:
      - erpc_network

  postgres:
    image: postgres:16 # Or your preferred Postgres version
    container_name: erpc_postgres_db
    restart: unless-stopped # Ensures restart on failure or host reboot
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist Postgres data using a named volume
    environment:
      # Credentials for Postgres database setup
      - POSTGRES_USER=${POSTGRES_ERPC_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ERPC_PASSWORD}
      - POSTGRES_DB=${POSTGRES_ERPC_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ERPC_USER} -d ${POSTGRES_ERPC_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - erpc_network

volumes:
  pgdata: # Define the named volume for Postgres data persistence

networks:
  erpc_network:
    driver: bridge
```
