### ISSUE TITLE
bug: RedisConnectorConfig does not support username option

### ISSUE THREAD

**Issue by wparr-circle** [erpc/erpc#248]
**Describe the bug**
RedisConnectorConfig has no way to set `username` to utilise a non-default user.

**To Reproduce**
N/A

**Expected behavior**
It's possible to configure a username.

**Screenshots**

**Relevant Logs:**
w/ the invalid configuration including `username`
```jsonl
{"level":"error","error":"failed to load configuration from ./erpc.yaml: yaml: unmarshal errors:\n  line 13: field username not found in type common.RedisConnectorConfig\n  line 24: field username not found in type common.RedisConnectorConfig","time":1745839823194,"message":"failed to load configuration"}
{"level":"error","time":1745839823194,"message":"failed to start erpc: failed to load configuration from ./erpc.yaml: yaml: unmarshal errors:\n  line 13: field username not found in type common.RedisConnectorConfig\n  line 24: field username not found in type common.RedisConnectorConfig"}
```

w/o specifying any `username`.
```jsonl
{"level":"warn","component":"sharedState","connector":"redis","task":"redis-connect/redis","error":"failed to connect to Redis: WRONGPASS invalid username-password pair or user is disabled.","time":1745839631992,"message":"initialization task failed"}

```

**Additional context**
Attempting to create a non-default redis user, with locked down access to certain keys and commands - we configured a user `restricted` on the target Redis instance.
After creation, attempted to configure the connector such as (not based on documentation, but a guess of what the config would look like:
```
      connectors:
        - id: short-term
          driver: redis
          redis:
            addr: <REDACTED>:6379
            username: restricted
            password: <REDACTED>
            connPoolSize: 10
            tls:
              enabled: true
```

Until switching to the restricted user, it was running perfectly fine with the `default` user - which is the default for the configured redis client.
https://github.com/erpc/erpc/blob/main/data/redis.go#L83
