### ISSUE TITLE
bug: subgraph complains latest block went backwards on Sonic chain

### ISSUE THREAD

**Issue by aramalipoor** [erpc/erpc#276]
**To Reproduce**
1. Use erpc version `0.0.46`

2. Use this erpc.yaml config:
```yaml
logLevel: warn
database:
  evmJsonRpcCache:
    connectors: 
      - id: memory-cache
        driver: memory
        memory:
          maxItems: 20000

    policies:
          # Example: Cache all methods with finalized data including empty responses
      - network: "*"
        method: "*"
        finality: finalized
        empty: ignore
        connector: memory-cache
        ttl: 180s
      # Example: Cache unfinalized data only for 5 seconds (getLogs of a recent block) except empty responses
      - network: "*"
        method: "*"
        finality: unfinalized
        empty: ignore
        connector: memory-cache
        ttl: 5s
      # Example: Cache unknown finalization data (eth_trace*) only for 10 seconds
      - network: "*"
        method: "*"
        finality: unknown
        empty: ignore
        connector: memory-cache
        ttl: 10s
      # Example: Cache realtime data only for 2 seconds (eth_blockNumber, eth_gasPrice, etc) to reduce costs yet fresh enough data
      - network: "*"
        method: "*"
        finality: realtime
        empty: ignore
        connector: memory-cache
        ttl: 1s


server:
  httpHostV4: 0.0.0.0
  httpPort: 4000
  maxTimeout: 60s
metrics:
  enabled: true
  hostV4: 0.0.0.0
  port: 4001
projects:
  - id: main

    networks:
      - architecture: evm
        evm:
          chainId: 146

    networkDefaults:
      directiveDefaults:
        retryPending: false
        retryEmpty: true
      failsafe:
        timeout:
          duration: 300s
        hedge:
          quantile: 0.99
          maxCount: 2
          minDelay: 100ms
          maxDelay: 1s
        retry:
          maxAttempts: 3
          delay: 0ms
      evm:
        integrity:
          enforceHighestBlock: true
          enforceGetLogsBlockRange: true

    upstreamDefaults:
      # Default group for all upstreams
      group: "default"
      # Default failsafe policies
      failsafe:
        timeout:
          duration: "60s"
        retry:
          maxAttempts: 1

    upstreams:
      - id: archive-sonic
        type: evm
        endpoint: ${SONIC_ENDPOINT}
        evm:
          chainId: 146
          statePollerInterval: 10s
          statePollerDebounce: 0.5s # block-time
          nodeType: archive
        routing:
          scoreMultipliers:
            - overall: 1
      - id: full-node-sonic
        type: evm
        endpoint: ${FULL_NODE_SONIC_ENDPOINT}
        evm:
          chainId: 146
          statePollerInterval: 10s
          statePollerDebounce: 0.5s # block-time
          nodeType: full
        routing:
          scoreMultipliers:
            - overall: 10
```
3. Run subgraph...
4. One of the node is 250 blocks behind...

**Expected behavior**
Always latest block is used, and it never goes backward

**Relevant Logs:**
Subgraph logs:
```jsonl
WARN Provider went backwards - ignoring this latest block, latest_block_head: 26479250, current_block_head: 26479472, provider: sonic, component: EthereumPollingBlockIngestor
```
