### ISSUE TITLE
feature: support a kubernetes provider

### ISSUE THREAD

**Issue by wparr-circle** [erpc/erpc#300]
**Is your feature request related to a problem? Please describe.**
We have recently been setting up eRPC for a handful of chains, a recurring pattern we're seeing emerging is having to embed into our configuration the likes of (ie. avoiding loadbalancing via a k8s service, to delegate the load balancing to eRPC instead):

```
upstreams:
  - upstream: http://geth-0.ethereum-mainnet.svc.cluster.local:8545
  - upstream: http://geth-1.ethereum-mainnet.svc.cluster.local:8545
  - upstream: http://geth-2.ethereum-mainnet.svc.cluster.local:8545
```

This provides us limited ability to scale our geth instances independently without having to make changes to the configuration of eRPC - which seems like a smell to us.

**Describe the solution you'd like**
We'd like the ability to discover the endpoints that back a given service through a kubernetes provider, similar to those defined here https://docs.erpc.cloud/config/projects/providers

Possibly reducing the configuration to, or similar:

```
upstreams:
- provider: kubernetes://geth.ethereum-mainnet.svc.cluster.local
```

We could probably do this in one of two ways:
1. Utilising a [headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) (ie. a service which is defined with `.spec.clusterIP` set `"None"`. This would cause a query of the service name to respond all the valid IPs selected by a given service.
2. Utilising a minimal [controller](https://kubernetes.io/docs/concepts/architecture/controller/) which creates a watch on endpoints associated with selected services, and reconciles these as IPs change. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
