### ISSUE TITLE
bug: configuration allows for mixing chains/networks

### ISSUE THREAD

**Issue by wparr-circle** [erpc/erpc#301]
**Describe the bug**
We recently had a small issue where whilst defining eRPC configuration, we accidentally mixed up ARB and AVAX - resulting a configuration similar to:
```yaml
      - id: avax-fuji
        upstreams:
          - endpoint: https://avalanche-fuji-c-chain-rpc.publicnode.com
          - endpoint: https://arbitrum-sepolia-rpc.publicnode.com
        upstreamDefaults:
          group: "default"
          evm:
            chainId: 43113
```

This ended up producing issues with the metrics `erpc_upstream_{block, finalization}_head_lag`, where the arbitrum upstream was considered the _most_ up to date upstream, despite not actually being an avalanche fuji upstream, which proceeded to be scored slightly higher allowing more traffic to weighted towards the abitrum upstream.

**To Reproduce**
1. Use erpc version (e.g `0.0.40`) 0.0.45 was used, should also affect 0.0.46

2. Use this erpc.yaml config:
```yaml
logLevel: debug
projects:
  - id: main
     upstreams:       
       - id: avax-fuji
          upstreams:
            - endpoint: https://avalanche-fuji-c-chain-rpc.publicnode.com
            - endpoint: https://arbitrum-sepolia-rpc.publicnode.com
          upstreamDefaults:
            group: "default"
            evm:
              chainId: 43113
# ...
```

3. Make this request:
```bash
curl --location 'http://localhost:4000/main/evm/43113' \
--header 'Content-Type: application/json' \
--data '{
    "method": "eth_getBlockByNumber",
    "params": [
        "latest",
        false
    ],
    "id": 9199,
    "jsonrpc": "2.0"
}'
```

**Expected behavior**
Requests should be proxied to avax only, as the only upstream which matches chainId 43113

**Screenshots**

**Relevant Logs:**
```jsonl
// ...
```

**Additional context**
