### ISSUE TITLE
Cache crashes under load (200+ rps)

### ISSUE THREAD

**Issue by OBlackmon3** [erpc/erpc#62]
Hello team!
My team has been using your caching solution and noticed that it tends to crash at around 200 requests per second. Do you have any suggestions for how we manage this or surpass this threshold?

For context, we used a locally running hardhat network for our RPC endpoint and a mix of rpc method calls to simulate typical load we expect for our service.

## Reproduction steps
We have been using the following erpc.yaml and reproduction script
`erpc.yaml`
```
logLevel: debug
database:
  evmJsonRpcCache:
    driver: memory
    #driver: redis
    #redis:
    #  addr: 'http://127.0.0.1'
    #  port: 6379
server:
  httpHostV4: 0.0.0.0
  httpPort: 4000
metrics:
  enabled: true
  hostV4: 0.0.0.0
  port: 4001
projects:
  - id: main
    networks:
      - architecture: evm
        evm:
          chainId: 31337
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxCount: 3
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
          hedge:
            delay: 3000ms
            maxCount: 2
    upstreams:
      - id: optimism-sepolia-1
        endpoint: 'http://127.0.0.1:8545/'
        rateLimitBudget: default-budget
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxCount: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
rateLimiters:
  budgets:
    - id: default-budget
      rules:
        - method: '*'
          maxCount: 10000
          period: 1s
    - id: global-blast
      rules:
        - method: '*'
          maxCount: 1000
          period: 1s
    - id: global-quicknode
      rules:
        - method: '*'
          maxCount: 300
          period: 1s
```
`reproduction script`
```
#!/bin/bash

function queryBlock() {
    local i=$1
    printf "[{ \"id\": %s, \"jsonrpc\": \"2.0\", \"method\": \"eth_getBlockByNumber\", \"params\": [\"latest\", false]}]" $i
}

function queryBlockNumber() {
    local i=$1
    printf "[{ \"id\": %s, \"jsonrpc\": \"2.0\", \"method\": \"eth_blockNumber\", \"params\": []}]" $i
}

function queryChainId() {
    local i=$1
    printf "[{ \"id\": %s, \"jsonrpc\": \"2.0\", \"method\": \"eth_chainId\", \"params\": []}]" $i
}


function query() {
    local i=$RANDOM
    local random_query=$(($i%3))
    local method="foo"
    case $random_query in
    0)
        method="eth_getBlockByNumber"
        query=$(queryBlock $i);;
    1)
        method="eth_chainId"
        query=$(queryChainId $i);;
    2)
        method="eth_blockNumber"
        query=$(queryBlockNumber $i);;
    *)
        echo "Invalid selection";;
    esac

    #echo $query
    echo "$method: $i"
    local j=$(curl -so - --request POST  http://localhost:4000/main/evm/31337 --header 'accept: application/json' --header 'content-type: application/json' --data "$query" | jq .[].id)
    echo "expected $i, got $j for $method"

}

for i in $(seq 1 200); do
    query &
done

wait
```
